version: "3"
services:
  web:
    build: .
    environment:
      - NODE_ENV=dev
    ports:
      - '3000:3000'
      - '3001:3001'
    volumes:
      - ./app:/home/app/app
      - ./assets:/home/app/assets
      - ./config:/home/app/config
      - ./test:/home/app/test
    command: npm run start
